# Generated by Django 4.1.3 on 2023-01-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_login_view_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=0, upload_to='image'),
        ),
    ]
