# Generated by Django 4.1.3 on 2023-01-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='image',
        ),
    ]
