# Generated by Django 4.1.3 on 2023-01-31 05:17

from django.db import migrations, models
import home.valiidators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_photo_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='photo',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(upload_to='image', validators=[home.valiidators.validate_file_size]),
        ),
    ]
